app:
    resource: "@AppBundle/Controller/"
#    prefix: /admin
    type:     annotation
easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:      annotation
    prefix:    /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
api:
    resource: "@AppBundle/Api/Controllers"
    prefix: /api
    type: annotation
